# Generated by Django 5.0.3 on 2024-03-20 16:56

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[student_app.validators.validate_email]),
        ),
    ]
