# Generated by Django 5.0.3 on 2024-03-20 17:25

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_locker_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='00-00-00', validators=[student_app.validators.validate_locker_combo]),
        ),
    ]
