# Generated by Django 5.0.3 on 2024-03-23 00:19

import grade_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[grade_app.validators.validate_grade]),
        ),
    ]
